version: "3.8"
services:
  api:
    image: trados-api:1.0
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db

  server:
    image: trados-server:1.0
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - api
    depends_on:
      - api
    ports:
      - 80:80

  db:
    image: trados-db:1.0
    container_name: db
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: tradingbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "!ChangeMe!"
      TZ: "Europe/Paris"
    ports:
      - "5432:5432"
    volumes:
      - ./db_datas:/var/lib/postgresql/data/
    restart: always


